### PR TITLE
Add: option to skip automatic redownload when removing from queue

### PR DESCRIPTION
**Pull request by gismo2004**
#### Database Migration
NO

#### Description
When trying to remove a failed/not matching download from queue with blacklisting, it should be possible to skip the automatic redownload as it would try to find another release which might be unwanted.

### CODE REVIEW

**Comment by gismo2004** [comment]
this is just an idea. if not suitable... drop it.

**Comment by Qstick** [comment]
I can see where this could be useful, but let’s wait till after #580 merges if that’s good.

**Comment by gismo2004** [comment]
@ta264 all done. :-)

**Comment by ta264** [comment]
Closing this in favour of #734, which just adds a test fixture for `RedownloadFailedDownloadService`

**Pull request closed without merging**
