### PR TITLE
Correct translation label

### PR DESCRIPTION
**Pull request by kromsam**
#### Database Migration
YES - XXXX | NO

#### Description
To show the proper translation of 'Lidarr Tags'.

### CODE REVIEW

**Review by Qstick — APPROVED** [review]

**Comment by bakerboy448** [comment]
tackled in the lidarr list changes PR fyi
https://github.com/Lidarr/Lidarr/pull/2868

**Comment by kromsam** [comment]
> tackled in the lidarr list changes PR fyi #2868

Ah cool. When I looked at the "frontend/src/Settings/ImportLists/ImportLists/EditImportListModalContent.js" file, line 276 (of the new version). The label still seemed to be 'ReadarrTags'. But now you know of it anyway :+1:

**Comment by ta264** [comment]
Incorporated in #2868

**Comment by ta264** [comment]
Thanks!

**Pull request closed without merging**
