### PR TITLE
Add Support for Flood

### PR DESCRIPTION
**Pull request by jordannick**
#### Database Migration
NO

#### Description
Adds support for the [Flood](https://flood.js.org/) download client. 

Based on jesec's additions to Sonarr [here](https://github.com/Sonarr/Sonarr/pull/4159) and Radarr [here](https://github.com/Radarr/Radarr/pull/5552), but with Lidarr flavor.

#### Issues Fixed or Closed by this PR

* #1922 
* #1923

### CODE REVIEW

**Comment by Qstick** [comment]
This looks pretty good just scanning it over. Will push it in with CI pass.

**Comment by jordannick** [comment]
Not sure why `
NzbDrone.Integration.Test.HttpLogFixture.should_log_on_error` failed in CI, it seems unrelated?

**Comment by ta264** [comment]
Please can you rebase and not merge? We don't allow merge commits on develop. Thanks!

**Comment by jordannick** [comment]
> Please can you rebase and not merge? We don't allow merge commits on develop. Thanks!

Done (and all tests are 👌 now!)

**Comment by jordannick** [comment]
@Qstick 

Any update on getting this merged in? 

Thank you

**Pull request merged**
