### PR TITLE
RED domain change

### PR DESCRIPTION
**Pull request by d-rez**
#### Database Migration
YES - 080

#### Description
RED domain has recently changed.
No tests were executed by me, might need some checks

#### Todos
- [ ] Tests

### CODE REVIEW

**Review by RobinDadswell — DISMISSED** [review]
This will require a database migration to update existing instances of RED in the database

**Comment by RobinDadswell** [comment]
> Thanks for taking a look, edited the description, are there any references / additional actions that should be done here?
> 
> Tried checking older PRs that needed DB migration, but I must be missing some context.

So it will need something like this done https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Datastore/Migration/190_update_awesome_hd_link.cs

**Comment by RobinDadswell** [comment]
Are you able to squash it all down into one Commit as well? Name the commit something like "Fixed: RED Indexer Domain Name"

**Comment by d-rez** [comment]
Thanks, appreciate the reference and tips. I've added the DB migration entry as well as restored Indexer warning for folks still using old URL within Gazelle API config. 

On the commit squashing, don't think I've done this before, will figure this out and update shortly 👍

**Review by mynameisbogdan — CHANGES_REQUESTED** [review]

**Review by mynameisbogdan — APPROVED** [review]

**Pull request merged**
