### PR TITLE
Allow adding/deleting individual albums

### LINKED ISSUE #179: Search and Add by album
Search by album name and add albums, needs metadata support first (in progress). Add should add the artist and only monitor the searched album

### LINKED ISSUE #207: Possible to add albums with "Various Artists" types?
I like soundtracks and broadway cast albums. Example https://musicbrainz.org/release/19e87c02-28df-4a89-ba7e-8f5ef474c36f

Is it possible to add these types as they don't have a set "Artist"

### LINKED ISSUE #272: adding Various Artists albums
kewl script by the way:) must appreciated!!

Is it possible to add various artists albums?

Ideally, adding by album name would be great,

Example of various artist  album is https://musicbrainz.org/release/26d1f2a3-177a-4ed7-bdf2-fb587483e4f6

Thanks in advance and keep up the GREAT work!!

### PR DESCRIPTION
**Pull request by ta264**
#### Database Migration
NO

#### Description
Allows adding/deleting individual albums.  First step towards VA support.

#### Todos
- [ ] Tests
- [ ] Documentation

#### Issues Fixed or Closed by this PR

* Fixes #179

### CODE REVIEW

**Comment by Qstick** [comment]
Fails during add of various album with following exception, will review/test more once we get the alias PR merged and the changes on this PR are a bit cleaner. 

```
System.Data.SQLite.SQLiteException
  HResult=0x80004005
  Message=constraint failed
NOT NULL constraint failed: Albums.AlbumType
  Source=System.Data.SQLite
  StackTrace:
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar()
   at Marr.Data.QGen.InsertQueryBuilder`1.Execute() in C:\Users\qstic\Documents\Visual Studio 2017\Projects\Lidarr\src\Marr.Data\QGen\InsertQueryBuilder.cs:line 140
   at Marr.Data.DataMapper.Insert[T](T entity) in C:\Users\qstic\Documents\Visual Studio 2017\Projects\Lidarr\src\Marr.Data\DataMapper.cs:line 728
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in C:\Users\qstic\Documents\Visual Studio 2017\Projects\Lidarr\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 112
   at NzbDrone.Core.Music.AlbumService.AddAlbum(Album newAlbum) in C:\Users\qstic\Documents\Visual Studio 2017\Projects\Lidarr\src\NzbDrone.Core\Music\AlbumService.cs:line 61
   at NzbDrone.Core.Music.AddAlbumService.AddAlbum(Album album) in C:\Users\qstic\Documents\Visual Studio 2017\Projects\Lidarr\src\NzbDrone.Core\Music\AddAlbumService.cs:line 52
   at Lidarr.Api.V1.Albums.AlbumModule.AddAlbum(AlbumResource albumResource) in C:\Users\qstic\Documents\Visual Studio 2017\Projects\Lidarr\src\Lidarr.Api.V1\Albums\AlbumModule.cs:line 99
   at Lidarr.Http.REST.RestModule`1.<set_CreateResource>b__42_0(Object options) in C:\Users\qstic\Documents\Visual Studio 2017\Projects\Lidarr\src\Lidarr.Http\REST\RestModule.cs:line 166
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Comment by karldonteljames** [comment]
Sorry to ask, I don't seem to be able to find the information.
Where do I find the url for the testing api?
I assume this is added to the metadata source in the settings? Thanks

**Comment by ta264** [comment]
This isn't ready for public testing yet I'm afraid. Also if you have run this branch in your database you'll probably need to restore a backup due to migration numbering conflicts.

**Comment by karldonteljames** [comment]
Sorry, I guess I mis-understood. I'm running version 0.6.2.883. 
I thought that changing the API endpoint was all I needed to do. 
Sorry for the confusion on my part.

**Comment by ta264** [comment]
I think this is ready for another look if you get chance.  It's mostly frontend work for the combined artist/album search results plus an add album API endpoint.

**Comment by Qstick** [comment]
One Issue, When adding a single Album from search, Artist is added with None metadata profile. However, if you go to artist edit on the artist details page none is not an option. So changing anything else will also force a metadata change.

**Comment by Qstick** [comment]
Seems to work now, only think I see is the various show up in search results issue.

**Comment by Qstick** [comment]
On the UI side:

May want to truncate text more here, given the new artist line.... or integrate the artist into the first line with the album name.
image

Also, is this release section just for additional reference? Takes up alot of space when expanded and doesn't seem to be used for anything.
image

**Pull request merged**
