### PR TITLE
Fixed: Newznab Artist search

### PR DESCRIPTION
**Pull request by gismo2004**
searchCriteria.Artist.Name includes "spaces", thus replaced by searchCriteria.ArtistQuery

### CODE REVIEW

**Comment by Qstick** [comment]
Good fix, but why all the code format changes

**Comment by gismo2004** [comment]
well, i thought it doesn't harm... I'm used to this kind of style (resharper would also do it like that) 

if it is not wanted, i remove it! no problem. 

Is there a code-style guide somewhere? (haven't found one)

**Comment by Qstick** [comment]
And thanks so much for all these fixes!

**Comment by gismo2004** [comment]
added braces again. 
I hope that my noop errors are not too annoying for you, but i'm no software developer in real live, so this is just my "hobby" :-) But I'm open for all help and critics --> I like to learn...

**Comment by Qstick** [comment]
Same for me, and I’ve made all the same errors lol. It’s no annoyance, everything is looking good!

**Pull request merged**
