### PR TITLE
Fixed: Update file paths correctly when moving artist

### LINKED ISSUE #1088: Lidarr doesn't update track paths after root change and manual move.
**Describe the bug**
Tracks are displayed in lidarr, but the path is still the old path from before the root folder change for the artist.

**To Reproduce**
1. Go to Mass Editor
2. Check one artist
3. Change root folder from /folder1 to /folder2
4. Click 'No, I'll move the files myself'
5. Go to artist
6. Refresh & scan, wait...
7. click Preview Rename
8. All tracks show old root path

**Expected behavior**
After a refresh & scan, track paths should be updated to actual location on disk.

**Screenshots**
image

**System info (please complete the following information):**
 - Lidarr Version: 0.7.1.1633
 - Operating System Armbian.  linuxserver/lidarr:preview

### PR DESCRIPTION
**Pull request by ta264**
#### Database Migration
NO

#### Description
Update artist file paths when manually moving artist

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* fixes #1088

### CODE REVIEW

**Comment by sebclark** [comment]
This is now updating the path correctly for files and artists and albums - thanks! However when you rescan the Artist folder the files/albums (which are no longer available) still show up as green found, and each file shows a duration of 0:00:00. They should turn red as missing.

image

**Comment by ta264** [comment]
Have you tried reloading the UI?

**Comment by sebclark** [comment]
I have reloaded the UI (shift) and restarted Lidarr. No joy. Event log shows it is trying to find the tag:

Tag reading failed for Q:\ServerFolders\Audio (Main)\album by artist\a\Adaline\Modern Romantics (2011)\Adaline - Modern Romantics - 01 - That's What You Do Best.mp3: Could not find a part of the path 'Q:\ServerFolders\Audio (Main)\album by artist\a\Adaline\Modern Romantics (2011)\Adaline - Modern Romantics - 01 - That's What You Do Best.mp3'.

**Comment by ta264** [comment]
Can you post a full trace log of the scan and also let me know where the files were and where they are now?

**Comment by sebclark** [comment]
20-5-14 23:23:43.2|Info|RefreshArtistService|Updating Info for Adaline
20-5-14 23:23:43.2|Info|RefreshAlbumService|Updating Info for Modern Romantics
20-5-14 23:23:43.3|Info|DiskScanService|Scanning Q:\ServerFolders\Music\Albums by Artist\
20-5-14 23:23:43.4|Warn|DiskScanService|Root folder Q:\ServerFolders\Music\Classical\ is empty.

Original Folder: Q:\ServerFolders\Music\Albums by Artist\Adaline
Mass Edited to folder (without letting Lidarr move the files): Q:\ServerFolders\Audio (Main)\album by artist\a\Adaline

Files are still in Q:\ServerFolders\Music\Albums by Artist\Adaline
(I) for the files shows them in Q:\ServerFolders\Music\Albums by Artist\Adaline and green exist/duration 00:00:00

**Comment by sebclark** [comment]
A small note - shouldn't it recreate the main artist folder when you move to a new root folder even if you say you will move the files yourself manually?

**Comment by sebclark** [comment]
After a lidarr restart and a system file scan task has run the files are now showing as missing.

**Pull request merged**
