### PR TITLE
Pull Sonarr commit 'New: Config file setting to disable log database'

### LINKED ISSUE #4785: Pull Sonarr commit 'New: Config file setting to disable log database'
Pull https://github.com/Sonarr/Sonarr/commit/92eab4b2e26741b7f20b6b7177418402cb15a3aa

```
git cherry-pick -ex 92eab4b2e26741b7f20b6b7177418402cb15a3aa
```

This commit has 4 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### LINKED ISSUE #4878: Pull Sonarr commit 'Fixed: Trimming disabled logs database'
Pull https://github.com/Sonarr/Sonarr/commit/d5dff8e8d6301b661a713702e1c476705423fc4f

```
git cherry-pick -ex d5dff8e8d6301b661a713702e1c476705423fc4f
```

This commit has 0 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

### PR DESCRIPTION
**Pull request by tieum**
#### Description

cherry picked from commits Sonarr/sonarr@92eab4b2e26741b7f20b6b7177418402cb15a3aa & Sonarr/sonarr@d5dff8e8d6301b661a713702e1c476705423fc4f

A config.xml and environment variable (LIDARR__LOG__DBENABLED) to disable the log database. This change disables the update and event pages on the frontend by returning default empty values.
This change is not breaking as it defaults to enabled if the configuration is omitted.

#### Database Migration
NO

#### Issues Fixed or Closed by this PR

* Fixes #4785 
* Fixes #4878

### CODE REVIEW

**Comment by bakerboy448** [comment]
Should add to the PR the cherry pick for https://github.com/Sonarr/Sonarr/commit/d5dff8e8d6301b661a713702e1c476705423fc4f as well

**Comment by tieum** [comment]
missed this thanks, done

**Comment by bakerboy448** [comment]
CI Failed

> /home/vsts/work/1/s/src/NzbDrone.Host/Startup.cs(247,14): error SA1513: Closing brace should be followed by blank line [/home/vsts/work/1/s/src/NzbDrone.Host/Lidarr.Host.csproj]

Would have failed to build locally too ;)

**Comment by tieum** [comment]
> Would have failed to build locally too ;)

@bakerboy448  Lesson learned 🙈️

**Pull request merged**
