### PR TITLE
improve TrackMatching

### PR DESCRIPTION
**Pull request by gismo2004**
#### Database Migration
 NO

#### Description
Improves TrackMatching a little bit

#### Todos
- [x] Tests
- [ ] Documentation

#### Issues Fixed or Closed by this PR
*

### CODE REVIEW

**Comment by Qstick** [comment]
I’ll test some, @danielunderwood Can you test this too. Probably would be good to add some unit tests for this as well.

**Comment by gismo2004** [comment]
unit testing is of course a good idea, but i can't imagine a scenario to test "real" problems. 

The code should always behave the same as before, since the order priority is the same, but extended with the swapped match. In my mind i'm not able to imagine a scenario where this would lead to a wrong match, but my head might... you know... ;-)

**Comment by Qstick** [comment]
I agree, don’t see much risk here. Was just saying because this is an area we don’t have unit test coverage and needed it before this too. 

A quick test fixture will just ensure it’s working like we know it is and provide future validation if someone else changes things. Should be very similar to the albumRepositoryFixture.cs here:

Lidarr/src/NzbDrone.Core.Test/MusicTests/AlbumRepositoryTests/AlbumRepositoryFixture.cs

**Comment by danielunderwood** [comment]
Did a bit of manual testing and seems to be working.

**Comment by Qstick** [comment]
How does this behave if there are two tracks named alike on a album. Ex. `Walk This Way (remix)` and `Walk This Way`.

I suppose since we are still matching track number also, this isn’t an issue really?

**Comment by gismo2004** [comment]
That's how it should work. I was also thinking about this, but in the end, it should make things better, because if the MB-DB provides us with `Walk This Way (remix)` and the file provides `Walk This Way` it will not match currently, even if the trackNumber is matching. So the question is: do we want to match such?

And what would be the rule for the suggested (Levenshtein) distance? would/should that match in this situation?

**Comment by Qstick** [comment]
All we have to go by is what others are using (beets/Picard/headphones). Most match based on a few different properties which combine to make a percentage match. And then a threshold is used to actually accept the match. I'll push this in and we can keep working on this.

**Comment by gismo2004** [comment]
We don't need to push it, if there are concerns on this. I would also be happy to go a step ahead and leave the old stuff as it is. If you think I'm of any help for the new stuff, let me know...

**Comment by Qstick** [comment]
Let's push release tonight without it and keep testing. I don't think there are issues but want to make sure before it goes to masses

**Pull request merged**
