### PR TITLE
Fixed: Filter exception repeatedly thrown by corrupt db migration

### PR DESCRIPTION
**Pull request by ta264**
#### Database Migration
NO

Fixes Sentry LIDARR-229

### CODE REVIEW

**Comment by Qstick** [comment]
Would there ever be cases when we want to see this? Ex. We screw up a migration that caused corruption..

**Comment by ta264** [comment]
I think we'd probably want to to catch this properly as a startup failure and wait for user input but thought we might want to get something sorted temporarily.

**Comment by Qstick** [comment]
That works, can we add a TODO comment

**Comment by ta264** [comment]
I've changed to a (hopefully) better fix - if we catch any exception in `DbFactory` and rethrow as a `LidarrStartupException` then we get caught by the existing bootloop protection [here](https://github.com/lidarr/Lidarr/blob/develop/src/NzbDrone.Console/ConsoleApp.cs#L40)

**Pull request merged**
