### PR TITLE
WIP: Checks the props for missing poster and deals with it accordingly

### PR DESCRIPTION
**Pull request by dabates**
#### Database Migration
NO

#### Description
If poster is undefined and the "prevProps" aren't the same as the "currentProps" .. we mark the image as having a problem.

#### Issues Fixed or Closed by this PR

*  #169

### CODE REVIEW

**Comment by Qstick** [comment]
Looks good, can you make same change to ArtistBanner.js?

**Comment by dabates** [comment]
Sure, I didn't knwo that artist banner was having the same issue :)

**Comment by Qstick** [comment]
They arnt used on the artist page, but would be good to keep code the same and handle just in case...

There seems to be another issue with the posters also which is also a issue with the banners. If you are on the index screen and have a poster that has no image and you delete that artist from there then the next artist (the one that takes its place in the grid) renders with no picture instead of bringing its picture in. I can send you a gif.

**Comment by dabates** [comment]
And that also happens with this version?  I'd need to setup a dummy library as Lidarr currently manages my library so deleting a artist might not be good :) but I can test this as well..

**Comment by Qstick** [comment]
yep just tested and it still happens, this does fix the posters issues on the artist detail screen nicely though 👍

**Pull request merged**
