### PR TITLE
Missing secondary type (Audio drama) added

### PR DESCRIPTION
**Pull request by sivn**
#### Screenshot (if UI related)

image

#### Todos
- [X] Tests
- [X] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [X] [Wiki Updates](https://wiki.servarr.com)

* Fixes Metadata Profile selector - "Audio drama" missing in "Edit Metadata Profile" (https://musicbrainz.org/doc/Release_Group/Type)

### CODE REVIEW

**Comment by bakerboy448** [comment]
For posterity:

> Audio drama
> An audio drama is an audio-only performance of a play (often, but not always, meant for radio). Unlike audiobooks, it usually has multiple performers rather than a main narrator.

**Comment by sivn** [comment]
Hey @bakerboy448, I just wanted to make sure that I'm not missing anything here. But there is nothing left to do for me here? One of the maintainers has to check the request and after that we're good to go, right?

**Review by ta264 — CHANGES_REQUESTED** [review]
This doesn't work unfortunately.  You need a database migration to add in the new secondary type to any existing profiles.

**Comment by bakerboy448** [comment]
Rebase don't merge

Merge commits are not allowed in \*Arrs

**Comment by sivn** [comment]
Thank you!

So the way to go is to close this request and reopen it after I fixed the migration?

**Comment by bakerboy448** [comment]
It can stay open

Just reset to pre-merge
Rebase and force push

**Comment by bakerboy448** [comment]
Rebase don't merge

this also reverted a ton of develop commits.  The develop branch you merged in is out of date with upstream develop

**Comment by sivn** [comment]
@bakerboy448 Yes, I tired that but it doesn't seem to work. Do you have a resource you could recommend where I can learn about how to do it correctly and what exactly the benefit is? Or I will just close the request and merge it locally. This won't happen again, sorry.

**Comment by bakerboy448** [comment]
GitHub has extensive documentation as does the entire internet.

Just google

**Comment by sivn** [comment]
@bakerboy448 @ta264 The database contains only the Id of the audio type (right?). Why is it necessary to do an migration? Should it be deleted and readded via the migration like this: `            Delete.Column("SecondaryAlbumTypes").FromTable("Artists");
         Alter.Table("Albums").AddColumn("SecondaryTypes").AsString().Nullable();`

**Comment by ta264** [comment]
You need to fix up the metadata profiles table. Try your running your code against an existing database and you'll see it falls over when you try to edit metadata profiles.

**Comment by sivn** [comment]
@bakerboy448 @ta264 I don't know why the Windows pipeline failed. I originally tested it on MacOS and Docker and now tried it with Visual Studio 2022 on Windows Server 2019 and it compiles successfully. I hope I didn't miss anything else! Thank you!

**Comment by Qstick** [comment]
Made a few tweaks to the migration based on our current standards and serialization. I'll get it merged if the tests are good this go. 

Thanks

**Review by Qstick — APPROVED** [review]

**Pull request merged**
