### PR TITLE
lossless compression of images

### PR DESCRIPTION
**Pull request by Fish2**

### CODE REVIEW

**Comment by Qstick** [comment]
Thanks

**Comment by Qstick** [comment]
@Fish2 you want to go ahead and change the outline image to Lidarr instead of Sonarr while you are at it?

**Comment by Fish2** [comment]
@Qstick Im not to good with SVGs sorry did have a little go but wasn't getting anywhere with it.

**Comment by Fish2** [comment]
I have now fixed the honeycomb on the svg as the clipping was off ready to pull if its all ok with you

**Comment by Qstick** [comment]
Thanks, I'll look at it tonight

**Pull request merged**
