### PR TITLE
New: Renamed Blacklist to Blocklist

### LINKED ISSUE #2356: Pull Sonarr commit 'New: Renamed Blacklist to Blocklist'
Pull https://github.com/Sonarr/Sonarr/commit/ead1371846b1f19cd49928052be0128bf7ccd41f

```
git cherry-pick -ex ead1371846b1f19cd49928052be0128bf7ccd41f
```

This commit has 47 conflict(s)

You can ask me to `close all`, `open pr here` or `open pr everywhere`

[AB#1398](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1398)

### PR DESCRIPTION
**Pull request by RobinDadswell**
#### Database Migration
YES - 050

#### Description
As part of the move to a more inclusive society, words like whitelist/blacklist are being moved away from in favour of the likes of allow list and blocklist. This replaces any references to the phrase blacklist with blocklist in the following areas: 
- Frontend User Visible
- Frontend Developer Visible
- Backend User Visible (e.g. logs) 
- Backend Developer Visible (with the exception of previous database migrations) 
- SQLLite Database

Blocklist was chosen in part via the Google Style Guide which discusses this matter and in tandem with both the Sonarr and Radarr/Lidarr/Readarr teams within the Sonarr Discord collaboration channel (https://discord.com/channels/383686866005917708/542785748768915456/859534462839685160)

#### Todos
- [x] Tests
- [x] Wiki Updates - @bakerboy448  if you'd be so kind :D 

#### Issues

- Fixes #2356

### CODE REVIEW

**Comment by RobinDadswell** [comment]
Once https://github.com/Radarr/Radarr/pull/6558 has landed I will move the frontend migration to this as well

**Comment by Qstick** [comment]
> Once [Radarr/Radarr#6558](https://github.com/Radarr/Radarr/pull/6558) has landed I will move the frontend migration to this as well

Landed

**Comment by RobinDadswell** [comment]
> > Once [Radarr/Radarr#6558](https://github.com/Radarr/Radarr/pull/6558) has landed I will move the frontend migration to this as well
> 
> 
> 
> Landed

I'll get the frontend migration in tonight

**Comment by Qstick** [comment]
> > > Once [Radarr/Radarr#6558](https://github.com/Radarr/Radarr/pull/6558) has landed I will move the frontend migration to this as well
> > 
> > 
> > Landed
> 
> I'll get the frontend migration in tonight

Got it covered here if you want to knock out Readarr later

**Review by Qstick — APPROVED** [review]

**Pull request merged**
